# Configuration
site_name: Hello C++
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Plugins
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: none
      width: 80%
      height: auto
      zoomable: false
      draggable: false
      auto_caption: false
      caption_position: bottom

# Repository
repo_name: Evilrabbit520/Hello-CPP
repo_url: https://github.com/Evilrabbit520/Hello-CPP
edit_uri: tree/main/docs
version: 1.0.0

extra:
  alternate:
    - name: 中文
      link: /
      lang: zh
    # - name: English
    #   link: /en/
    #   lang: en
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Evilrabbit520/Hello-CPP
    - icon: fontawesome/solid/code
      link: https://github.com/Evilrabbit520/Hello-CPP/code
  generator: false

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - tables
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Copyright
copyright: Copyright &copy; 2024 Wang Yujia

# Page tree
nav:
- 第 0 章 &nbsp; 前言:
    # [icon: material/book-open-outline]
    - Preface/index.md
    - 0.1 &nbsp; 关于本书: Preface/aboutTheBook.md
    - 0.2 &nbsp; 如何使用本书: Preface/howToUse.md
    - 0.3 &nbsp; 小结: Preface/summary.md
- 第 1 章 &nbsp; 基础知识:
    # [icon: material/book-open-outline]
    - BasicKnowledge/index.md
    - 1.1 &nbsp; C 语言简介及原理: BasicKnowledge/c-cppSynopsis.md
    - 1.2 &nbsp; 面向对象和泛型: BasicKnowledge/oop-gp.md
    - 1.3 &nbsp; C++ 简介及标准: BasicKnowledge/cppHistory.md
    - 1.4 &nbsp; 安装IDE: BasicKnowledge/installIDE.md
- 第 2 章 &nbsp; 踏上 C++ 之旅:
    # [icon: material/book-open-outline]
    - StartLearningCpp/index.md
    - 2.1 &nbsp; 正式学习 C++: StartLearningCpp/startCpp.md
    - 2.2 &nbsp; C++ 语句: StartLearningCpp/cppStatement.md
    - 2.3 &nbsp; C++ 语句的扩展: StartLearningCpp/cppOtherStatement.md
- 第 3 章 &nbsp; 数据操作:
    # [icon: material/book-open-outline]
    - DataOperation/index.md
    - 3.1 &nbsp; 简单变量及类型: DataOperation/simpleVariables.md
    - 3.2 &nbsp; const 常量限定符: DataOperation/constantQualifier.md
    - 3.3 &nbsp; 浮点类型: DataOperation/floatingPointTypes.md
    - 3.4 &nbsp; 浮点类型: DataOperation/readingIncludeFiles.md
    - 3.5 &nbsp; C++ 算数操作符: DataOperation/arithmeticOperators.md
    - 3.6 &nbsp; 操作符重载: DataOperation/operatorOverload.md
    - 3.7 &nbsp; 类型转换: DataOperation/typeConversion.md
    - 3.8 &nbsp; 小结: DataOperation/summary.md
- 第 4 章 &nbsp; 复合类型:
    # [icon: material/book-open-outline]
    - CompositeTypes/index.md
    - 4.1 &nbsp; 数组初识: CompositeTypes/arrays.md