name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-glightbox
          pip install mkdocs mkdocs-material mkdocs-print-site-plugin

      - name: Build MkDocs site
        run: |
          mkdocs build


      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            if [ -d "${{ secrets.SERVER_TARGET }}" ]; then
              if [ -w "${{ secrets.SERVER_TARGET }}" ]; then
                echo "Target directory is writable."
              else
                echo "Target directory is not writable. Changing permissions..."
                chmod 777 ${{ secrets.SERVER_TARGET }}
              fi
            fi
          rm: true # 在上传前删除目标文件夹
          source: ./site/*
          target: ${{ secrets.SERVER_TARGET }}

      - name: Clean up
        run: |
          rm -rf ./site/
